Repository lab-brussels-1/home, pull requests merged in 2022-03, with the labels that each got.

#121 PR for adding MMihailova.md into Students dio folder
  admin/modules.yml
  haring_banner.jpeg
  student-bios/MMikhailova.md
Labels: week-1, deliverable

#131 Nazgul bio
  package-lock.json
  package.json
  student-bios/NazgulM.md
  student-bios/assets/Naza.jpg
Labels: week-1, deliverable, individual

#132 My bio
  .vscode/settings.json
  student-bios/shewitttt.md
Labels: week-1, deliverable, individual

#136 Newfile
  student-bios/MahaLubbad.md
Labels: week-2, deliverable, individual

#159 Alexanderism551
  student-bios/alexanderism55.md
Labels: week-2, deliverable, individual

#167 Dnyandeo about my information
  .DS_Store
  student-bios/.DS_Store
  student-bios/Dnyandeo33.md
  student-bios/assets/Dnyandeo.jpeg
Labels: week-1, deliverable, individual

#166 Fenny W Jacobs Bio
  student-bios/FennyWilriani.md
Labels: documentation, week-1, individual

#169 Haneefa: Student bio
  student-bios/Haneefa-Shaik.md
  student-bios/assets/Haneefa-photo.jpg
Labels: week-1, deliverable, individual

#176 Marie Josee student bio
  student-bios/Ufitamahoro.md
  student-bios/assets/Benz.jpeg
  student-bios/minjupgeorge.md
Labels: week-1, deliverable, individual

#162 Hadoan149: student bio
  student-bios/assets/hadoanpic.jpg
  student-bios/hadoan149.md
Labels: week-1, deliverable, individual

#189 zerubabel4
  student-bios/zerubabel4.md
Labels: week-1, deliverable, individual

#186 Zeynep-student bio
  student-bios/Melati5.md
Labels: week-1, deliverable, individual

#191 Zeynep-bio: punctuation fix
  package-lock.json
  student-bios/Melati5.md
Labels: week-1, deliverable, individual

#192 Abdijibar1
  student-bios/Melati5.md
  student-bios/abdijibar1.md
Labels: week-1, deliverable, individual

#170 Cristobal Alexander Lopez : Bio
  student-bios/Alexander-Segovia.md
Labels: week-1, deliverable, individual

#205 created ali.md in student-bios
  cheat-sheets/github.md
  student-bios/alihaidermalik20.md
Labels: deliverable

#208 Add file and folder
  people/readme.md
Labels: practice
